services:
  - type: web
    name: invoice-generator
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20.17.1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html